spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeetscmaker/environment-variable-repo.git
          
  application:
    name: config-server
 
server:
  port: 8888
